### ISSUE TITLE
arm64 docker container support

### ISSUE THREAD

**Issue by berceanu** [ricardo-fonseca/zpic#18]
The new Mac lineup all use M1 processors, with `arm64` architecture. The `zamb/zpic` container only supports the `amd64` arch. 

The docker [documentation](https://docs.docker.com/docker-for-mac/apple-silicon/#known-issues) states

> In summary, running Intel-based containers on Arm-based machines should be regarded as “best effort” only. We recommend running arm64 containers on Apple Silicon machines whenever possible.

**Comment by ricardo-fonseca** [comment]
We are looking into M1 / ARM support for the Docker image, but we currently don't have access to any test hardware so this will take a while. In the meantime if you want native ARM support you will need to download the source and compile it locally.
