### ISSUE TITLE
matplotlib animations not working inside docker container

### ISSUE THREAD

**Issue by berceanu** [ricardo-fonseca/zpic#19]
The following notebooks contain animations:

`classroom/Electrostatic Two-Stream.ipynb`
`tutorial/Animation.ipynb`

and they both give this error:

`ModuleNotFoundError: No module named ipympl`

**Comment by ricardo-fonseca** [comment]
Worked well on my tests with the latest commit, I'll leave it open for a while in case something else is not working.

**Comment by berceanu** [comment]
Confimed, they both work now in the latest version of the docker container.

**Comment by ricardo-fonseca** [comment]
Thanks for the feedback, I'm closing this issue
